# Cloudflare Tunnel Configuration
# 
# IMPORTANT: Replace the following values with your actual details:
# 1. YOUR_TUNNEL_ID_HERE - Get from: cloudflared tunnel list
# 2. yourdomain.com - Replace with your actual domain
#
# Example tunnel ID format: dc1f834e-63f2-4b5f-9d2f-368433b182a6

tunnel: dc1f834e-63f2-4b5f-9d2f-368433b182a6
credentials-file: ~/.cloudflared/dc1f834e-63f2-4b5f-9d2f-368433b182a6.json

ingress:
  # File upload service
  - hostname: files.salamander.blue
    service: http://localhost:5001
  
  # Main application
  - hostname: salamander.blue
    service: http://localhost:5000
  
  # Catch-all rule (must be last)
  - service: http_status:404

# Optional: Disable HTTP/2 if you experience issues
# http2Origin: false

# Optional: Enable metrics endpoint (accessible at localhost:20242/metrics)
# metrics: localhost:20242
